### ISSUE TITLE
[Feat] 썰 열람페이지 UI 구현

### ISSUE THREAD

**Issue by kimssoyeon** [THE-T-DEPth/spill-the-tea-web#1]
## 🌏Summary

>  썰 열람페이지 UI 구현

## ✔️ Task & Description

- [x] title component 구현
- [x] tag component 구현
- [x] content component 구현
- [x] 음성 기능 구현
- [x] modal 구현
- [x] login 여부에 따른 기능 구현
- [x] 댓글 component 구현
- [x] 대댓글 component 구현
- [x] 댓글 신고 기능 구현
- [x] DetailView page 구현
- [x] routing

## 🐸 Reference

-
