### ISSUE TITLE
[Feat] 게시물 작성 페이지 UI 구현

### ISSUE THREAD

**Issue by kimssoyeon** [THE-T-DEPth/spill-the-tea-web#16]
## 🌏Summary

>  게시물 작성 페이지 UI 구현

## ✔️ Task & Description

- [ ] 모달 component 구현
- [ ] 글 작성 component 구현
- [ ] 글꼴 및 색상 선택 구현
- [ ] 제출 및 커뮤니티 가이드 component 구현
- [ ] 소설화 component 구현
- [ ] 짤 검색 component 구현
- [ ] 음성 출력 component 구현
- [ ] 키워드 지정 component 구현

## 🐸 Reference

-
